export const table1 = [
  {
    title: "Ticket Management",
    content: [
      {
        label: "Unlimimited Mailboxes",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Unlimited Tickets",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Customizable Statuses",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Customizable Priorities",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Ticket Custom Fields",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Custom Domain Mapping",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Multilingual Agent Portal",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Agent Collision",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Work Schedules",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Custom Roles and Permissions",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Ticket Tagging",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Email Notifications",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Bulk Editing",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Satisfaction Surveys",
        card1: false,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Custom Ticket Queues",
        card1: false,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Kanban view of tickets",
        card1: false,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Proactive Agent Collision",
        card1: false,
        card2: false,
        card3: true,
        card4: true,
      },
      {
        label: "SLA Live Timer",
        card1: false,
        card2: false,
        card3: true,
        card4: true,
      },
      {
        label: "Task Management",
        card1: false,
        card2: false,
        card3: true,
        card4: true,
      },
      {
        label: "Asset Management",
        card1: false,
        card2: false,
        card3: true,
        card4: true,
      },
      {
        label: "Unlimited Assets",
        card1: false,
        card2: false,
        card3: true,
        card4: true,
      },
      {
        label: "Category Wise Statuses",
        card1: false,
        card2: false,
        card3: false,
        card4: true,
      },
      {
        label: "Attachment Store",
        card1: "50 GB",
        card2: "500 GB",
        card3: "1 TB",
        card4: "2 TB",
      },
    ],
  },
];
export const table2 = [{}];
