export const table1 = [
  {
    title: "Ticket Management",
    content: [
      {
        label: "Unlimimited Mailboxes",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Unlimimited Categories",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Unlimited Tickets",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Customizable Statuses",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Customizable Priorities",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Ticket Custom Fields",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Custom Domain Mapping",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Multilingual Agent Portal",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Agent Collision",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Work Schedules",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Custom Roles and Permissions",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Ticket Tagging",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Email Notifications",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Bulk Editing",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Satisfaction Surveys",
        card1: false,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Custom Ticket Queues",
        card1: false,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Kanban view of tickets",
        card1: false,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Proactive Agent Collision",
        card1: false,
        card2: false,
        card3: true,
        card4: true,
      },
      {
        label: "SLA Live Timer",
        card1: false,
        card2: false,
        card3: true,
        card4: true,
      },
      {
        label: "Task Management",
        card1: false,
        card2: false,
        card3: true,
        card4: true,
      },
      {
        label: "Asset Management",
        card1: false,
        card2: false,
        card3: true,
        card4: true,
      },
      {
        label: "Unlimited Assets",
        card1: false,
        card2: false,
        card3: true,
        card4: true,
      },
      {
        label: "Category Wise Statuses",
        card1: false,
        card2: false,
        card3: false,
        card4: true,
      },
      {
        label: "Attachment Store",
        card1: "50 GB",
        card2: "500 GB",
        card3: "1 TB",
        card4: "2 TB",
      },
    ],
  },
  {
    title: "Customer Management",
    content: [
      {
        label: "Unlimited Contacts",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Import Contacts",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Contact Custom Fields",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Unlimited Contact Groups",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Contact Group Custom Fields",
        card1: false,
        card2: false,
        card3: true,
        card4: true,
      },
    ],
  },
  {
    title: "Help Desk Automation",
    content: [
      {
        label: "Smart Rule Automation",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Canned Actions (Macros)",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Ticket Templates",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Automatic Time Tracking",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "SLA management",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "SLA Breach Notification",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Round Robin Ticket Assignment",
        card1: false,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Round Robin Ticket Assignment on Active Agents",
        card1: false,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Load Balanced Ticket Assignment",
        card1: false,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Scheduled Tickets",
        card1: false,
        card2: false,
        card3: true,
        card4: true,
      },
      {
        label: "Agent Scripting",
        card1: false,
        card2: false,
        card3: false,
        card4: true,
      },
    ],
  },
  {
    title: "Support Center",
    content: [
      {
        label: "Self-Service Knowledge Base",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Internal Knowledge Base",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Knowledge Base Notifications",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Support Portal Builder",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "SEO optimization for Knowledge Base",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Knowledge base Drafts",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Automatic Sitemap Generation",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Client Portal",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Multilingual Knowledge Base",
        card1: false,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Code Editor for Support Center",
        card1: false,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Multi-brand Help Desk with SSL Support #",
        card1: false,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Multi-branding with Custom Domain",
        card1: false,
        card2: "5 brands",
        card3: "15 brands",
        card4: "25 brands",
      },
      {
        label: "Contact Group Specific Knowledge Base",
        card1: false,
        card2: false,
        card3: true,
        card4: true,
      },
    ],
  },
  {
    title: "Help Desk Reportng",
    content: [
      {
        label: "Dashboard",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Report Filters",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Export Tickets to CSV or Excel",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Ticket Inflow Report",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Help Desk Performance Report",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Agent Activity Report",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Ticket Distribution Report",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Time Spent Report",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Contact Report",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Canned Actions Report",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Satisfaction Survey Report",
        card1: false,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "SLA Performance Report",
        card1: false,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Custom Field Report",
        card1: false,
        card2: false,
        card3: true,
        card4: true,
      },
      {
        label: "Contact Group Report",
        card1: false,
        card2: false,
        card3: true,
        card4: true,
      },
      {
        label: "Scheduled Reports",
        card1: false,
        card2: false,
        card3: true,
        card4: true,
      },
      {
        label: "Ticket Life Cycle Report",
        card1: false,
        card2: false,
        card3: true,
        card4: true,
      },
      {
        label: "Asset Report",
        card1: false,
        card2: false,
        card3: true,
        card4: true,
      },
      {
        label: "Smart Rule Metrics",
        card1: false,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Custom Dashboard",
        card1: false,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Reporting History",
        card1: "Last 1 year",
        card2: "Last 3 year",
        card3: "Last 5 year",
        card4: "All Time",
      },
    ],
  },
  {
    title: "Security",
    content: [
      {
        label: "SOC 2 Type II Compliance",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Role-Based Security",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "SSL Certificate Hosting (Custom Domain)",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Single Sign-on (Azure, Google, SAML, Okta & more)",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Session-Based Security",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Automatic Data Deletion/Redaction",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Two Factor Authentication",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Data Encryption - Rest and Transit",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "SSO Lockout Recovery",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Your Own Single Sign-on (JWT)",
        card1: false,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Digitally Signed Emails (DKIM)",
        card1: false,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Password Policy Management",
        card1: false,
        card2: false,
        card3: true,
        card4: true,
      },
      {
        label: "IP-Based Restriction",
        card1: false,
        card2: false,
        card3: true,
        card4: true,
      },
      {
        label: "Audit Logs",
        card1: "Basic",
        card2: "Basic",
        card3: "Basic",
        card4: "Advanced",
      },
    ],
  },

  {
    title: "Support",
    content: [
      {
        label: "Self-Service Portal",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "HappyFox University",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Migration Assistance $",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Customizable Support Widget",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "EU Data Center Hosting (optional)",
        card1: false,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Uptime SLA",
        card1: false,
        card2: false,
        card3: true,
        card4: true,
      },
      {
        label: "Customer Success Manager",
        card1: false,
        card2: false,
        card3: false,
        card4: true,
      },
      {
        label: "Email Support (PST)",
        card1: "5AM-5PM (Mon-Fri)",
        card2: "24/7",
        card3: "24/7",
        card4: "24/7",
      },
      {
        label: "Live Chat Support (PST)",
        card1: "8AM-5PM (Mon-Fri)",
        card2: "5AM-5PM (Mon-Fri)",
        card3: "24/7",
        card4: "24/7",
      },
      {
        label: "Phone Support (PST)",
        card1: false,
        card2: "8AM-5PM (Mon-Fri)",
        card3: "5AM-5PM (Mon-Fri)",
        card4: "24/7",
      },
    ],
  },
  {
    title: "Third Party Integrations",
    content: [
      {
        label: "Aircall",
        card1: false,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Facebook",
        card1: "3 Pages",
        card2: "5 Pages",
        card3: "7 Pages",
        card4: "10 Pages",
      },
      {
        label: "JIRA",
        card1: false,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Microsoft Teams",
        card1: false,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Slack",
        card1: false,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "SmartSignin",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Stripe",
        card1: false,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "SugarCRM",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "SurveyMonkey",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Twitter",
        card1: "2 Accounts",
        card2: "5 Accounts",
        card3: "7 Accounts",
        card4: "10 Accounts",
      },
      {
        label: "WhatsApp",
        card1: false,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Wrike",
        card1: false,
        card2: false,
        card3: true,
        card4: true,
      },
      {
        label: "Zapier",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Zoho CRM",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
    ],
  },
  {
    title: "Inbuilt Integrations",
    content: [
      {
        label: "Embeddable Widget",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Webhooks",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "REST API (requests per minute)",
        card1: "100",
        card2: "200",
        card3: "400",
        card4: "800",
      },
    ],
  },
  {
    title: "Mobile",
    content: [
      {
        label: "Help Desk Mobile App",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Asset Manager App",
        card1: false,
        card2: false,
        card3: true,
        card4: true,
      },
    ],
  },
];

export const table2 = [
  {
    title: "Ticket Management",
    content: [
      {
        label: "Unlimimited Mailboxes",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Unlimited Tickets",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Customizable Statuses",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Customizable Priorities",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Ticket Custom Fields",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Custom Domain Mapping",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Multilingual Agent Portal",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Agent Collision",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Work Schedules",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Custom Roles and Permissions",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Ticket Tagging",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Email Notifications",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Bulk Editing",
        card1: true,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Satisfaction Surveys",
        card1: false,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Custom Ticket Queues",
        card1: false,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Kanban view of tickets",
        card1: false,
        card2: true,
        card3: true,
        card4: true,
      },
      {
        label: "Proactive Agent Collision",
        card1: false,
        card2: false,
        card3: true,
        card4: true,
      },
      {
        label: "SLA Live Timer",
        card1: false,
        card2: false,
        card3: true,
        card4: true,
      },
      {
        label: "Task Management",
        card1: false,
        card2: false,
        card3: true,
        card4: true,
      },
      {
        label: "Asset Management",
        card1: false,
        card2: false,
        card3: true,
        card4: true,
      },
      {
        label: "Unlimited Assets",
        card1: false,
        card2: false,
        card3: true,
        card4: true,
      },
      {
        label: "Category Wise Statuses",
        card1: false,
        card2: false,
        card3: false,
        card4: true,
      },
      {
        label: "Attachment Store",
        card1: "50 GB",
        card2: "500 GB",
        card3: "1 TB",
        card4: "2 TB",
      },
    ],
  },
];
